title: Funniest's Blog
description: I love computer. Because, it have power which can realize impossible idea.

url: https://https://github.com/Funniest
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: Funniest
  twitter: 
  facebook: 
  email: funniest.ms@gmail.com
  linkedin: 

google_analytics: ""

disqus:
    shortname: Funniest
